services:

  db:
    image: postgres:15
    container_name: volis_db

    environment:
      POSTGRES_DB: volis
      POSTGRES_USER: volis
      POSTGRES_PASSWORD: volis

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data


  backend:
    build: ./backend
    container_name: volis_backend

    depends_on:
      - db

    ports:
      - "3000:3000"

    environment:
      DB_HOST: db
      DB_NAME: volis
      DB_USER: volis
      DB_PASS: volis
    volumes:
      - ./backend:/app


  frontend:
    image: nginx:alpine
    container_name: volis_frontend

    ports:
      - "8080:80"

    volumes:
      - ./frontend:/usr/share/nginx/html:ro


volumes:
  pgdata:
